machine:
  nodeLabels:
    # Label for Proxmox node pool identification
    <label-zone>/proxmox-pools: main-talos-master
    # Remove external load balancer exclusion label for MetalLB
    node.kubernetes.io/exclude-from-external-load-balancers:
      $patch: delete

  features:
    # Enable Talos Kubernetes API Access feature for Proxmox CCM
    kubernetesTalosAPIAccess:
      enabled: true
      allowedRoles:
        - os:reader
      allowedKubernetesNamespaces:
        - kube-system

cluster:
  # Allow workload scheduling on control plane nodes (for HA with fewer nodes)
  allowSchedulingOnControlPlanes: true
  coreDNS:
    # Disable default CoreDNS to use custom one with OPNsense homelab configuration
    disabled: true
  etcd:
    extraArgs:
      # Expose etcd metrics endpoint
      listen-metrics-urls: http://0.0.0.0:2381
  network:
    # Disable default CNI to use Cillium
    cni:
      name: custom
      urls:
        # Cilium CNI for Talos
        - https://<static-host>/talos-init/talos-cni-cilium-v1.18.4.yaml
  externalCloudProvider:
    enabled: true
    manifests:
      # Custom CoreDNS for Talos with OPNsense homelab configuration
      - https://<static-host>/talos-init/coredns-custom-talos-opnsense-homelab-v1.13.1.yaml
      # Proxmox CCM Access Secrets and Deployment
      - https://<static-host>/talos-init/proxmox/proxmox-cloud-controller-manager-secrets.yaml
      - https://<static-host>/talos-init/proxmox-cloud-controller-manager-v0.12.2.yaml
      # Proxmox CSI Access Secrets and Deployment
      - https://<static-host>/talos-init/proxmox/proxmox-csi.yaml
      - https://<static-host>/talos-init/proxmox/proxmox-csi-secrets.yaml
      - https://<static-host>/talos-init/proxmox-csi-plugin-v0.16.0.yaml
  extraManifests:
    # kubelet-serving-cert-approver for automatically approve rotate-server-certificates
    - https://<static-host>/talos-init/kubelet-serving-cert-approver-v0.10.0-ha.yaml
    # metrics-server for cluster resource metrics
    - https://<static-host>/talos-init/metrics-server-v0.8.0-ha.yaml
