machine:
  nodeLabels:
    # Label for Proxmox node pool identification
    <label-zone>/proxmox-pools: main-talos-worker

cluster:
  network:
    # Disable default CNI to use Cillium
    cni:
      name: custom
      urls:
        - https://<static-host>/talos-init/talos-cni-cilium-v1.18.4.yaml
