apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  name: external-secets-kustomization
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: eks-kloia-test
  source:
    repoURL: git@github.com:kholisrag/labirin.git
    path: modules/argocd/external-secrets/1.1.0
    targetRevision: main
  destination:
    name: in-cluster
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
