apiVersion: ENC[AES256_GCM,data:cxj1dENKWdt05pxmsKd+rspF426HWQ==,iv:Salv3z89AMdEWDe56IqPhDeuH554+ejGTTCZyPEgI68=,tag:Dls4oZOXsEUBmglXk9WcBw==,type:str]
kind: ENC[AES256_GCM,data:D3YOfXvS5x/bDMKW0i7r65sg,iv:xkSq86+orfR7GO3WMaacVm8rM6xODfnSrAb5NJHUNnU=,tag:1RB3qlKHC3mtEjbU8lbfSQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hVhlKys=,iv:gCGeHmQQU5eRPq5h1mpFrHY7Ht0t6JLbRs/P8fTp8NA=,tag:nG++IrzweoC6DKBc+YIGew==,type:str]
spec:
    provider:
        vault:
            server: ENC[AES256_GCM,data:v7kSlm2CuZi2RmDyYHsNlEZVW5Bjv4pFMKWvnOGnIh6gFJ/zmWWMLTFLYp9KnnhU,iv:YiIbX+aHuLpYfrycyDOiWUoU9AwnjagfCdiatbxlHwM=,tag:tYJ9ZAlZlw9cbsi7L74LcQ==,type:str]
            path: ENC[AES256_GCM,data:DZXUIBUtYg==,iv:p21lnepTqb/TnSfVl1cO4rf0iqmp3YBhIuEOvqD+ghA=,tag:W2BBM2Fjiitlr3fyHTbWTg==,type:str]
            version: ENC[AES256_GCM,data:yUc=,iv:JxNKKlo9ATdxMIl4NvksN5PX84aC+ZMyXfTY4lkKDuw=,tag:lRNXBjZ0wXH3WWPxtRG1fg==,type:str]
            auth:
                tokenSecretRef:
                    name: ENC[AES256_GCM,data:eLIhCfVxI/snTLs=,iv:ML/lr/OJew7npMGHUfoIwkNRJXjemFMW0H3qWRMj6Y8=,tag:CmzM02VjPlwLVaSvm/731Q==,type:str]
                    namespace: ENC[AES256_GCM,data:oTi/MfY9yzpclg69TPjawA==,iv:V9g6zeAIzIko9i2r0mGUQDVjt6RR4TXrnww+H1D9GeQ=,tag:yMNShovygyEaMtOauTq1LA==,type:str]
                    key: ENC[AES256_GCM,data:swD5K1o=,iv:4sCekLhH95kjaETo1KUpcdiW6FgN9aGL87Bmqh1NJwc=,tag:4GotD4ewpWfHITnKQDqjtw==,type:str]
sops:
    age:
        - recipient: age17nqlfm7qj72hgjfs82vqwcfatqymqngpwvp7v999crs2t5a6tu5sd0vcp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeGtobDVTb2FzOXJ6ZDRC
            YzhMbVQ5d1JxbDNQNzA2WHFrZ1FXUTVvZGh3CmJvR0xIdHAranY2MGpSR3RSdDZm
            dS9naHNJL2E3ZDdJQUtCRTE3dnpFV00KLS0tIGNkNVQ1RTNQYTB0UWZUeDNPcnd1
            QTB6b2RRYUtMcmNDS1ZGQ2lpd0pucDQKEarmOOOjr4m1xC6YaG+SgVPC+YOSg45V
            Mj9VR/GV1PUeUDoatYA+1xX0ZaH++QsqNolwjy3Insgh6U77S0HNzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lgmay2ca3aydsltkxjhz2qc6ep4rqdpjneye3lxra0h3a5k37aeqjj2ue4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZGMxNjdVd3ZEcTgxOWdm
            cldSK1BML29XcVVCeHlVWGFTU1B2WnNGRG5JCnNjcTBXTHAxSVB3aFhkT0MrQkdZ
            aDFIYnJyeXM2aGZkS2lvREhXRGdPQWsKLS0tIGdNQ1BPcFo1bHVNZWtVdmFqR2Yr
            OWM1eVhvcDNlb3FxZlF3eTZlK09RZ0kKMDqQsjwD2YdI2+d76tX1y8Fk1dS8zTtB
            aNBmIvtuIg0s4iKEAhAiDCopkLJ+2NKFTdFinNXsVX0ZqL93TEkeqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T08:54:06Z"
    mac: ENC[AES256_GCM,data:GmGJGqh9nuafaqFLQO4lHROUWkAvTxOFtTNnLy5MEEVjCEN8GPFbRU6NkEJ1f60Ro4TGWeU2qibI9fTANo6hymqkzYHyiWsTwObGpJZ+ObjaMrTMYNoBc/JMNcj09R0iDMP2kP8LqO6xvgdrgyA3ckYuIs5rwY1s5cGstyBCM1Q=,iv:CAPsIaf3pcC4qQrWYtF23cCxk96l+DXfOsAq4ixTxic=,tag:GAl0qs7kgCuc8Oxk9+LoVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:Ymg=,iv:rMm1U29hWC+eJiPYpaal8iXgMbaVsy3KeMpIUF0zfrc=,tag:znXPFRMgN0U4Zzvu9WYBWw==,type:str]
kind: ENC[AES256_GCM,data:D0ZW4Yjc,iv:dTQKrCal4izrYQqbjTW5bZhHyZWw4Psvyx1VpNV3IRA=,tag:wKwrN9OXNYEbFg4njiUV+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SN2s+vYiSGt7d/A=,iv:hlZWwkqgUvV0ilJbavfmAc8VIG7pU/RNh73mbNQJFtA=,tag:vzKlN1SEsPp/5lshT7C0hw==,type:str]
    namespace: ENC[AES256_GCM,data:DrDbA0JWsQO67zlirGZmAA==,iv:sxIuLdwoRXcU4sjypEvNKPoThEu47+MIj5QIs8mM8Fo=,tag:OJYmudru5zkHabmpj5liHA==,type:str]
stringData:
    token: ENC[AES256_GCM,data:6ZjqyIeZ9Cbzey28GlyDBfpp8gzALwu82qe3lg==,iv:zSBgSYqHWyANEBE37LSGYR38v57E4wlgq1f6WFXo2UM=,tag:Lm+O7RYYCVl6Ga5rXKQcyA==,type:str]
sops:
    age:
        - recipient: age17nqlfm7qj72hgjfs82vqwcfatqymqngpwvp7v999crs2t5a6tu5sd0vcp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeGtobDVTb2FzOXJ6ZDRC
            YzhMbVQ5d1JxbDNQNzA2WHFrZ1FXUTVvZGh3CmJvR0xIdHAranY2MGpSR3RSdDZm
            dS9naHNJL2E3ZDdJQUtCRTE3dnpFV00KLS0tIGNkNVQ1RTNQYTB0UWZUeDNPcnd1
            QTB6b2RRYUtMcmNDS1ZGQ2lpd0pucDQKEarmOOOjr4m1xC6YaG+SgVPC+YOSg45V
            Mj9VR/GV1PUeUDoatYA+1xX0ZaH++QsqNolwjy3Insgh6U77S0HNzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lgmay2ca3aydsltkxjhz2qc6ep4rqdpjneye3lxra0h3a5k37aeqjj2ue4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZGMxNjdVd3ZEcTgxOWdm
            cldSK1BML29XcVVCeHlVWGFTU1B2WnNGRG5JCnNjcTBXTHAxSVB3aFhkT0MrQkdZ
            aDFIYnJyeXM2aGZkS2lvREhXRGdPQWsKLS0tIGdNQ1BPcFo1bHVNZWtVdmFqR2Yr
            OWM1eVhvcDNlb3FxZlF3eTZlK09RZ0kKMDqQsjwD2YdI2+d76tX1y8Fk1dS8zTtB
            aNBmIvtuIg0s4iKEAhAiDCopkLJ+2NKFTdFinNXsVX0ZqL93TEkeqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T08:54:06Z"
    mac: ENC[AES256_GCM,data:GmGJGqh9nuafaqFLQO4lHROUWkAvTxOFtTNnLy5MEEVjCEN8GPFbRU6NkEJ1f60Ro4TGWeU2qibI9fTANo6hymqkzYHyiWsTwObGpJZ+ObjaMrTMYNoBc/JMNcj09R0iDMP2kP8LqO6xvgdrgyA3ckYuIs5rwY1s5cGstyBCM1Q=,iv:CAPsIaf3pcC4qQrWYtF23cCxk96l+DXfOsAq4ixTxic=,tag:GAl0qs7kgCuc8Oxk9+LoVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
