# yaml-language-server: $schema=https://raw.githubusercontent.com/evilmartians/lefthook/refs/heads/master/schema.json
pre-commit:
  parallel: true
  jobs:
    - name: check secrets with `gitleaks`
      run: gitleaks git --pre-commit --staged --redact

    - name: check broken links with `lychee`
      run: lychee {staged_files}

    - name: check typos with `typos`
      run: typos --config .typos.toml --force-exclude --write-changes {staged_files}
      stage_fixed: true

    - name: format hcl files with `terragrunt`
      glob: "*.{hcl}"
      run: terragrunt hcl fmt {staged_files}
      stage_fixed: true

    - name: format terraform/opentofu files with `tofu`
      glob: "*.{tofu,tf}"
      run: tofu fmt {staged_files}
      stage_fixed: true
