roles:
  - name: sebdanielsson.cloudflared
    version: "2.4.3"
collections:
  - name: community.general
    version: ">=11.4.1,<12.0.0"
  - name: community.proxmox
    version: ">=1.4.0,<2.0.0"
  - name: ansible.posix
    version: ">=2.1.0,<3.0.0"
