---
- name: Install QEMU Guest Agent
  hosts: all
  become: true
  tasks:
    - name: Install QEMU Guest Agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
    - name: Start QEMU Guest Agent
      service:
        name: qemu-guest-agent
        state: started
        enabled: true
