apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  name: external-secrets-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: eks-kloia-test
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 1.1.0
    helm:
      releaseName: external-secrets
      valuesObject:
        installCRDs: true
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::888688231966:role/external-secrets-20251202192518393500000001"
  destination:
    name: in-cluster
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
