# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-addons
  namespace: flux-system
spec:
  interval: 15m
  path: "live/fluxcd/proxmox/talos/main-talos-k8s-cluster/essentials/cluster-addons"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
