---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cloudflare-tunnel-ingress-controller.strrl.dev/backend-protocol: "https"
    cloudflare-tunnel-ingress-controller.strrl.dev/proxy-ssl-verify: "off"
  name: argocd
  namespace: argocd
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: argocd-kloia-test.khol.is
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 443
            path: /
            pathType: Prefix
