apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: essentials-kustomization
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: proxmox-talos-main-talos-cluster
  source:
    repoURL: git@github.com:kholisrag/labirin.git
    path: live/argocd/proxmox/talos/main-talos-k8s-cluster/essentials
    targetRevision: main
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
      - ServerSideApply=true
